---
title: "Investigacion sobre las universidades"
author: "INTEGRANTES: Camila Gonzalez, Luciana Parallela
Camila Rondon, Mauri, Lucas Colosimo"
date: "2025-05-28"
output: 
  html_document: default
---

# INTRODUCCION

x

## Definición de los objetivos del analisís

#### La *problemática* que hemos elegido para el presente trabajo se basa en los factores que hacen que haya menor o mayor tasa de egresados en las universidades de Buenos Aires. En base a esta problemática y a partir de los data sets seleccionados y a su respectivo análisis, hemos elegido los siguientes factores a analizar:

-   Cuál es la diferencia en cantidad de graduados en instituciones públicas o privadas (tanto a nivel general y en carreras específicas.

-   Cómo varía la cantidad de egresados s/ área disciplinar (Área de ingeniería tiene más egresados que en otras áreas). (Gráfico de torta o barras: eje x: área disciplinar, eje y: cantidad de egresados)

-   Carreras que tienen menor/mayor cantidad de egresados. (Abogacía, contador público, enfermería).

-   Carreras con mayor y menor retención estudiantil (Con mayor egresados/retención son abogacía, contador público y enfermería; con menor retención (más cantidad de ingresantes pero menor cantidad de egresados).

-   Cómo varía la cantidad de graduados según su edad y género.

## Justificación de la elección del dataset

El dataset de los "Anuarios Estadísticos" del sistema universitario es la fuente más adecuada para estudiar la evolución en diversas áreas, las causas de ello y diferencias en la tasa de egreso universitaria en Buenos Aires. Además la información es confiable porque es oficial, completa, accesible, comparable entre años, y centrada en variables directamente vinculadas al fenómeno de estudio.

#Probando **negrita** 